'use strict';
/**
 * Tasveer — Our Little Scrapbook. (Boyfriend Day family, template 2.)
 *
 * "Tasveer" (तस्वीर / تصویر) means "photograph" or "picture" in Hindi/Urdu —
 * the perfect name for a polaroid scrapbook.
 *
 * Tilted polaroids scroll into view one by one via IntersectionObserver, each
 * taped to the page with washi tape corners. A heart doodle draws itself
 * between the second and third polaroids as the reader scrolls past it. Tapping
 * any polaroid opens it full-size in a lightbox. A handwritten note card at the
 * end closes the scrapbook. Up to eight photos with captions and dates; photos
 * left blank show beautifully styled placeholder art.
 *
 * Zero external media: placeholders are inline SVG data URIs generated by the
 * script. Fonts: Caveat + Inter (Google Fonts).
 * Reduced motion: scroll reveals are instant, heart draws immediately.
 */

const DEFAULT_PHOTOS = [
  { caption: 'the day we walked nowhere in particular', date: 'one sunny afternoon' },
  { caption: 'your terrible, perfect coffee order',     date: 'every single morning' },
  { caption: 'movie night, all elbows & blankets',      date: 'that rainy friday' },
  { caption: "the laugh i'd know anywhere",             date: 'mid-story, always' },
  { caption: 'us, being us',                            date: 'my favourite anyway' },
];

/** The demo ships real sample photos (assets/bfday-demo/, written at boot). */
const DEMO_PHOTOS = [
  { photo: '/assets/bfday-demo/couple-1.jpg', caption: 'the day we walked nowhere in particular', date: 'one sunny afternoon' },
  { photo: '/assets/bfday-demo/couple-7.jpg', caption: 'your terrible, perfect coffee order',     date: 'every single morning' },
  { photo: '/assets/bfday-demo/couple-3.jpg', caption: 'movie night, all elbows & blankets',      date: 'that rainy friday' },
  { photo: '/assets/bfday-demo/couple-9.jpg', caption: "the laugh i'd know anywhere",             date: 'mid-story, always' },
  { photo: '/assets/bfday-demo/couple-2.jpg', caption: 'us, being us',                            date: 'my favourite anyway' },
];

module.exports = {
  slug: 'polaroid-scrapbook',
  family: 'bfday',
  name: 'Tasveer',
  category: 'Love',
  price: 0,
  currency: 'INR',
  description: 'Our Little Scrapbook — tilted polaroids that scroll into view one by one, a self-drawing heart doodle, a lightbox, and a handwritten note at the end. Add up to eight photos with captions.',
  thumbnail_url: '',
  version: 1,
  editable: true,
  displayField: 'senderName',

  fields: [
    {
      id: 'senderName',
      type: 'text',
      label: 'Your name',
      required: true,
      maxLength: 40,
      placeholder: 'Rahul',
      hint: 'Shown on the note card at the end of the scrapbook.',
    },
    {
      id: 'scrapbookTitle',
      type: 'text',
      label: 'Title of the scrapbook',
      maxLength: 60,
      default: 'our little scrapbook',
      hint: 'The big heading at the top.',
    },
    {
      id: 'scrapbookSub',
      type: 'text',
      label: 'Subtitle under the title',
      maxLength: 60,
      default: 'a keepsake, just for you',
    },
    {
      id: 'photos',
      type: 'list',
      label: 'The polaroids',
      itemLabel: 'Polaroid',
      addLabel: 'Add a polaroid',
      minItems: 1,
      maxItems: 8,
      shape: [
        { id: 'photo',   type: 'image', label: 'Photo' },
        { id: 'caption', type: 'text',  label: 'Caption', required: true, maxLength: 80 },
        { id: 'date',    type: 'text',  label: 'Date underneath', maxLength: 40 },
      ],
      default: DEFAULT_PHOTOS,
      hint: 'Leave photos blank — the design draws its own placeholder art for each one.',
    },
    {
      id: 'noteText',
      type: 'text',
      label: 'The final note',
      maxLength: 80,
      default: 'happy boyfriend day, from me',
      hint: 'The handwritten card at the end. Try "happy boyfriend day, from Rahul".',
    },
    {
      id: 'noteDate',
      type: 'text',
      label: 'Under the note',
      maxLength: 60,
      default: 'always & then some',
    },
  ],

  steps: [
    {
      title: 'Who it’s from',
      heading: 'Who is it from?',
      intro: 'Your name goes on the note card at the end of the scrapbook.',
      fields: ['senderName'],
    },
    {
      title: 'The title',
      heading: 'Title and subtitle',
      intro: 'These appear at the very top of the scrapbook.',
      fields: ['scrapbookTitle', 'scrapbookSub'],
    },
    {
      title: 'The polaroids',
      heading: 'Your polaroids',
      intro: 'Each photo gets a caption and an optional date. Leave photos blank — the design draws its own placeholder art.',
      fields: ['photos'],
    },
    {
      title: 'The note',
      heading: 'The final note',
      intro: 'A handwritten card, tilted at a gentle angle, that closes out the scrapbook.',
      fields: ['noteText', 'noteDate'],
    },
  ],

  create: {
    eyebrow: 'Tasveer · Our Little Scrapbook',
    headline: 'A scrapbook, just for him.',
    intro: 'Tilted polaroids scroll into view one by one, each taped to the page. A heart doodle draws itself as he scrolls. Tap any polaroid to open it full-size. Add up to eight photos, or leave them blank — the design draws its own art.',
    noun: 'scrapbook',
    designHeading: 'Five polaroids and a note',
    designIntro: 'Photos scroll in as you reach them, each at its own angle. A heart doodle draws itself between them as you scroll.',
    scenes: [
      'polaroids scroll into view one by one, each tilted at a different angle',
      'a heart doodle draws itself on the page as you scroll past it',
      'tap any polaroid to open it full-size in a lightbox',
      'a handwritten note card closes it all out',
    ],
    previewCta: 'Scroll it exactly as he will.',
    previewHelp: 'Tap a polaroid to open it full-size.',
    resultLine: 'Send him the link. The scrapbook is waiting.',
  },

  /** /polaroid-scrapbook/demo, the gallery thumbnail and the detail page. */
  demo: {
    bgmSong: 'gJLVTKhTnog',
    senderName: 'Rahul',
    scrapbookTitle: 'our little scrapbook',
    scrapbookSub: 'a keepsake, just for you',
    photos: DEMO_PHOTOS,
    noteText: 'happy boyfriend day, from Rahul',
    noteDate: 'always & then some',
  },

  sections: ['header', 'polaroids', 'note'],
  theme: {
    bg: '#FFFDF8', ink: '#2B2118', accent: '#B85C48', soft: '#F2C4BC',
    motif: 'heart', ampersand: false, serifCase: 'lower', layout: 'scroll',
  },
};
