'use strict';
const { logoFull } = require('../lib/brand');

function ganapatiCreatePage() {
  const field = (name, key, type = 'text', max = 120, required = false) => `<div class="field"><label for="${name}"><span data-i18n="${key}"></span>${required ? ' <span aria-hidden="true">*</span>' : ''}</label>${type === 'textarea' ? `<textarea id="${name}" name="${name}" maxlength="${max}" rows="3"${required ? ' required' : ''}></textarea>` : `<input id="${name}" name="${name}" type="${type}"${type === 'text' ? ` maxlength="${max}"` : ''}${required ? ' required' : ''}>`}</div>`;
  return `<!DOCTYPE html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#fbf4ed"><title>Ganapati Aagman · Paigaam</title><link rel="icon" href="/favicon.svg"><link rel="stylesheet" href="/ganapati/create.css"><script src="/ganapati/create.js" defer></script></head>
<body><header class="masthead"><a href="/" aria-label="Paigaam">${logoFull(128)}</a><div class="language-control"><label for="language" data-i18n="language"></label><select id="language" name="language"><option value="en">English</option><option value="hi">हिन्दी</option><option value="mr">मराठी</option></select></div></header>
<main id="wizard"><section class="intro"><p class="eyebrow" data-i18n="eyebrow"></p><h1 data-i18n="heading"></h1><p class="intro-copy" data-i18n="intro"></p></section>
<div class="workspace"><aside class="journey"><p class="eyebrow" data-i18n="yourInvitation"></p><ol id="progress" aria-label="Progress">${['design','language','family','event','photos','preview'].map((key,i)=>`<li data-progress="${i}"><span class="step-number">0${i+1}</span><span data-i18n="${key}"></span></li>`).join('')}</ol><p class="aside-note" data-i18n="asideNote"></p></aside>
<div class="paper"><p id="stepCounter" class="eyebrow"></p><form id="ganapatiForm" novalidate>
<section data-step="0" class="step"><div class="design-grid"><div class="design-copy"><h2 tabindex="-1" data-i18n="designTitle"></h2><p data-i18n="designBody"></p><span class="seal" data-i18n="templateName"></span><p class="hint" data-i18n="designHint"></p></div><figure class="template-art"><img src="/ganapati/media/formation-end.jpg" alt="Ganapati invitation design" id="templateImage"><figcaption data-i18n="artCaption"></figcaption></figure></div></section>
<section data-step="1" class="step" hidden><h2 tabindex="-1" data-i18n="languageTitle"></h2><p data-i18n="languageBody"></p><div class="language-cards" role="group" id="languageCards"><button type="button" data-language="en"><b>English</b><span>Welcome home, Bappa</span></button><button type="button" data-language="hi"><b>हिन्दी</b><span>घर पधारो, बप्पा</span></button><button type="button" data-language="mr"><b>मराठी</b><span>बाप्पा, घरी या</span></button></div><p class="hint" data-i18n="languageHint"></p></section>
<section data-step="2" class="step" hidden><h2 tabindex="-1" data-i18n="familyTitle"></h2><p data-i18n="familyBody"></p><p class="hint" data-i18n="requiredHint"></p>${field('familyName','familyName','text',120,true)}<div class="field-grid">${field('fatherName','fatherName')}${field('motherName','motherName')}</div>${field('familyMembers','familyMembers','textarea',600)}${field('customMessage','customMessage','textarea',2000)}<p class="hint" data-i18n="messageHint"></p></section>
<section data-step="3" class="step" hidden><h2 tabindex="-1" data-i18n="eventTitle"></h2><p data-i18n="eventBody"></p><div class="field"><label for="festivalYear" data-i18n="year"></label><input id="festivalYear" type="number" min="2026" max="2100" step="1" required value="2026" inputmode="numeric"><p class="hint" id="dateHint"></p><a class="source" href="https://www.drikpanchang.com/festivals/ganesh-chaturthi/ganesh-chaturthi-date-time.html" target="_blank" rel="noopener noreferrer" data-i18n="source"></a></div><div class="field-grid">${field('eventDate','eventDate','date',0,true)}${field('eventTime','eventTime','time',0,true)}</div><p class="time-note" data-i18n="timezone"></p>${field('venueName','venueName','text',160,true)}${field('address','address','textarea',500,true)}</section>
<section data-step="4" class="step" hidden><h2 tabindex="-1" data-i18n="photosTitle"></h2><p data-i18n="photosBody"></p><div class="upload-box"><button class="button secondary" type="button" id="choosePhotos" data-i18n="choosePhotos"></button><input id="photoFiles" type="file" accept="image/jpeg,image/png,image/webp" multiple hidden><p class="hint" data-i18n="photoHint"></p></div><p id="photoCount" class="hint" aria-live="polite"></p><div id="photoList" class="photo-list"></div><p class="hint" data-i18n="uploadNote"></p></section>
<section data-step="5" class="step" hidden><h2 tabindex="-1" data-i18n="previewTitle"></h2><p data-i18n="previewBody"></p><div id="review" class="review"></div><div class="preview-callout"><span class="mini-flower" aria-hidden="true">✦</span><p data-i18n="previewHint"></p><button type="button" id="savePreview" class="button primary" data-i18n="savePreview"></button></div><p id="previewState" class="hint" aria-live="polite"></p><button type="button" id="publish" class="button publish" data-i18n="generate" disabled></button><p class="hint" data-i18n="publishHint"></p></section>
<div id="formError" class="error" role="alert" hidden></div><p id="status" class="status" role="status" aria-live="polite"></p><nav class="step-nav"><button type="button" id="back" class="button text-button" data-i18n="back"></button><button type="submit" id="next" class="button primary" data-i18n="continue"></button></nav>
</form></div></div></main>
<section id="publishedResult" class="result paper" hidden aria-labelledby="resultTitle"><p class="eyebrow" data-i18n="readyEyebrow"></p><h1 id="resultTitle" tabindex="-1" data-i18n="readyTitle"></h1><p data-i18n="readyBody"></p><label for="publishedUrl" data-i18n="invitationLink"></label><input id="publishedUrl" readonly><div class="result-actions"><a id="openPublished" class="button primary" target="_blank" rel="noopener noreferrer" data-i18n="openInvitation"></a><button type="button" id="copyLink" class="button secondary" data-i18n="copyLink"></button><a id="whatsapp" class="button secondary" target="_blank" rel="noopener noreferrer" data-i18n="whatsapp"></a></div><p id="shareStatus" role="status" aria-live="polite"></p></section>
<footer><span data-i18n="footer"></span></footer>
<dialog id="previewDialog" aria-labelledby="previewDialogTitle"><div class="preview-toolbar"><h2 id="previewDialogTitle" data-i18n="yourPreview"></h2><div><button type="button" id="fullscreen" class="button secondary" data-i18n="fullscreen"></button><button type="button" id="closePreview" class="button primary" data-i18n="closePreview"></button></div></div><p class="preview-help" data-i18n="previewInteraction"></p><div id="frameHost"></div><p id="modalStatus" role="status" aria-live="polite"></p></dialog>
<noscript><p class="error">Please enable JavaScript to create your invitation. निमंत्रण बनाने के लिए JavaScript चालू करें। निमंत्रण तयार करण्यासाठी JavaScript सुरू करा.</p></noscript></body></html>`;
}
module.exports = { ganapatiCreatePage };
